name: Bandit Security Analysis

on:
  push:
    branches:
      - master  # Change to your default branch
  
jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the appropriate version

    - name: Install Bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit
      run: |
        bandit -r . -f json -o bandit_report.json
        cat bandit_report.json  # Display the report in logs

    - name: Upload Bandit Report
      uses: actions/upload-artifact@v2
      with:
        name: bandit-report
        path: bandit_report.json

    - name: Check Bandit results
      run: |
        if grep -q '"issue_severity": "HIGH"' bandit_report.json; then
          echo "High severity issues found!"
          exit 1
        fi
